FROM node:16-alpine3.15 as build-stage
WORKDIR /view
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# CREATE NGINX SERVER
FROM nginxinc/nginx-unprivileged  as prod-stage
COPY --from=build-stage /view/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]